import './globals.css'
import { Inter } from 'next/font/google'

import NavBar from './navBar/navBar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Quince Creative',
  description: 'Generated by create next app',
  icons: {
    icon: { url: '/vertical_logo-small.png', type: 'image/svg/png' },
    shortcut: { url: '/vertical_logo-small.png', type: 'image/svg/png' },
  },
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main>
          <NavBar/>
          {children}
        </main>
      </body>
    </html>
  )
}
