import Link from 'next/link'
import './globals.css'
import { Inter } from 'next/font/google'

import NavBar from './navBar/navBar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Quince Creative',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main>
          <NavBar/>
          {children}
        </main>
      </body>
    </html>
  )
}
