
import './globals.css'
import { Inter } from 'next/font/google'

import Header from './header/Header'
import FooterB from "./Footer/footer";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Quince Creative',
  description: 'Generated by create next app',
  icons: {
    icon: { url: '/images/logo/logoGif.gif', type: 'image/svg/png/gif' },
    shortcut: { url: '/images/logo/logoGif.gif', type: 'image/svg/png/gif' },
  },
}


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main>

          <Header/>
          {children}
        </main>
   <FooterB />
      </body>
    </html>
  )

}
